[2023-11-12T21:29:51.440+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509
[2023-11-12T21:29:51.441+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_17'
[2023-11-12T21:29:51.474+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509
[2023-11-12T21:29:51.476+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_17'
[2023-11-12T21:29:51.508+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: simulator_dag_17.setup_and_run_simulator_task_17 scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-12T21:29:51.519+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: simulator_dag_17.setup_and_run_simulator_task_17 scheduled__2023-11-11T00:00:00+00:00 [queued]>
[2023-11-12T21:29:51.520+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-11-12T21:29:51.539+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): setup_and_run_simulator_task_17> on 2023-11-11 00:00:00+00:00
[2023-11-12T21:29:51.572+0000] {standard_task_runner.py:57} INFO - Started process 529 to run task
[2023-11-12T21:29:51.576+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'simulator_dag_17', 'setup_and_run_simulator_task_17', 'scheduled__2023-11-11T00:00:00+00:00', '--job-id', '44', '--raw', '--subdir', 'DAGS_FOLDER/timeseries.py', '--cfg-path', '/tmp/tmpuvurp82q']
[2023-11-12T21:29:51.580+0000] {standard_task_runner.py:85} INFO - Job 44: Subtask setup_and_run_simulator_task_17
[2023-11-12T21:29:51.649+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509
[2023-11-12T21:29:51.650+0000] {logging_mixin.py:154} INFO - Failed to change /opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_17 permission to 509: [Errno 1] Operation not permitted: '/opt/***/logs/dag_id=simulator_dag_17/run_id=scheduled__2023-11-11T00:00:00+00:00/task_id=setup_and_run_simulator_task_17'
[2023-11-12T21:29:51.658+0000] {task_command.py:416} INFO - Running <TaskInstance: simulator_dag_17.setup_and_run_simulator_task_17 scheduled__2023-11-11T00:00:00+00:00 [running]> on host 84c765240aba
[2023-11-12T21:29:51.758+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='simulator_dag_17' AIRFLOW_CTX_TASK_ID='setup_and_run_simulator_task_17' AIRFLOW_CTX_EXECUTION_DATE='2023-11-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-11T00:00:00+00:00'
[2023-11-12T21:29:51.892+0000] {logging_mixin.py:154} INFO - Standard Output: 
[2023-11-12T21:29:51.894+0000] {logging_mixin.py:154} INFO - Standard Error: python: can't open file 'Task1/main.py': [Errno 2] No such file or directory
[2023-11-12T21:29:51.898+0000] {logging_mixin.py:154} INFO - this is hiiiim <Thread(Thread-1, initial)>
[2023-11-12T21:29:51.900+0000] {python.py:194} INFO - Done. Returned value was: None
[2023-11-12T21:29:51.915+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=simulator_dag_17, task_id=setup_and_run_simulator_task_17, execution_date=20231111T000000, start_date=20231112T212951, end_date=20231112T212951
[2023-11-12T21:29:51.981+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-12T21:29:51.999+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
